# GitGuardian configuration
# https://docs.gitguardian.com/ggshield-docs/configuration

version: 2

# Version 2 configuration format
secret:
  # Paths to ignore for secret detection
  # These are data files that frequently trigger false positives
  # Using gitignore-style glob patterns
  ignored_paths:
    # Reports directory - all files
    - 'reports/**'
    # Root level JSON files
    - 'plugins.json'
    - 'found_prs.json'
    - 'jenkins_prs.json'
    - 'report.json'
    # Root level data files
    - 'plugin_evolution.csv'
    - 'recipes-to-apply.csv'
    - 'top-250-plugins.csv'
    - 'depends_on_java_8.txt'
    - 'depends_on_java_11.txt'
    - 'manual_jdk25_plugins.txt'
    # Plugin list files with date stamps
    - 'plugins_jdk11_main_*.txt'
    - 'plugins_jdk11_main_20*.txt'
    # Plugin version files
    - 'plugins_with_versions.txt'
    - 'top_plugins_with_versions.txt'
    - '*plugins_with_versions.txt'

  # Ignore specific patterns that are not secrets
  # These are common patterns in Jenkins plugin data that look like secrets but aren't
  ignored_matches:
    - name: Ignore Jenkins plugin URLs
      match: https://github.com/jenkinsci/
    - name: Ignore update center URLs
      match: https://updates.jenkins.io/
    - name: Ignore repository paths
      match: jenkinsci/.*-plugin
