# GitGuardian configuration
# https://docs.gitguardian.com/ggshield-docs/configuration

version: 2

# Version 2 configuration format
secret:
  # Paths to ignore for secret detection
  # These are data files that frequently trigger false positives
  # Using gitignore-style glob patterns
  ignored_paths:
    # Reports directory - all files (anchored to root)
    - '/reports/**'
    - 'reports/**'
    # Root level JSON files (anchored with / to match only at root)
    - '/plugins.json'
    - '/found_prs.json'
    - '/jenkins_prs.json'
    - '/report.json'
    # Root level data files (anchored with / to match only at root)
    - '/plugin_evolution.csv'
    - '/recipes-to-apply.csv'
    - '/top-250-plugins.csv'
    - '/depends_on_java_8.txt'
    - '/depends_on_java_11.txt'
    - '/manual_jdk25_plugins.txt'
    # Plugin list files with date stamps (anchored with / to match only at root)
    - '/plugins_jdk11_main_*.txt'
    - 'plugins_jdk11_main_*.txt'
    # Plugin version files (anchored with / to match only at root)
    - '/plugins_with_versions.txt'
    - '/top_plugins_with_versions.txt'
    # Match any file ending with plugins_with_versions.txt (not anchored)
    - '*plugins_with_versions.txt'
    # Date-stamped output files
    - 'plugins-output.txt'
    - '/plugins-output.txt'

  # Ignore specific patterns that are not secrets
  # These are common patterns in Jenkins plugin data that look like secrets but aren't
  ignored_matches:
    - name: Ignore Jenkins plugin URLs
      match: https://github.com/jenkinsci/
    - name: Ignore update center URLs
      match: https://updates.jenkins.io/
    - name: Ignore repository paths
      regex: jenkinsci/.*-plugin
