#!/bin/bash

# group-prs.sh <input-json-file> <plugins-json-file>
# Replace <input-json-file> with the path to the JSON file generated by compute-stats.sh.
# Replace <plugins-json-file> with the path to the plugins.json file.

# Input JSON file (passed as a parameter)
INPUT_JSON="$1"
PLUGINS_JSON="$2"

# Validate that the input JSON file exists and is readable
if [ ! -r "$INPUT_JSON" ]; then
  echo "Error: Input file '$INPUT_JSON' does not exist or is not readable" >&2
  exit 1
fi

# Check if the plugins JSON file exists and is less than one day old
if [ ! -f "$PLUGINS_JSON" ] || [ $(find "$PLUGINS_JSON" -mtime +1 -print) ]; then
  echo "Downloading plugins.json..."
  curl -L https://updates.jenkins.io/current/update-center.actual.json -o "$PLUGINS_JSON"
fi

# Validate that the plugins JSON file exists and is readable
if [ ! -r "$PLUGINS_JSON" ]; then
  echo "Error: Plugins file '$PLUGINS_JSON' does not exist or is not readable" >&2
  exit 1
fi

# Filter PRs related to Jenkins plugins
./filter-prs.sh "$INPUT_JSON" "$PLUGINS_JSON"

# Use the filtered PRs JSON file for grouping
FILTERED_JSON="filtered_prs_$(basename "$INPUT_JSON")"

# Group PRs by title and status
GROUPED_PRS=$(jq '
  group_by(.title) |
  map({
    title: .[0].title,
    merged: map(select(.state == "MERGED")) | length,
    open: map(select(.state == "OPEN")) | length,
    closed: map(select(.state == "CLOSED")) | length,
    prs: .
  })' "$FILTERED_JSON")

# Output the grouped PRs to a new JSON file
OUTPUT_JSON="grouped_prs_$(basename "$INPUT_JSON")"
echo "$GROUPED_PRS" > "$OUTPUT_JSON"

echo "Grouped PRs have been saved to $OUTPUT_JSON"

# Activate the virtual environment (if it exists)
if [ -d "venv" ]; then
  source venv/bin/activate
else
  echo "Virtual environment not found. Please create it first."
  exit 1
fi

# Run the Python script to upload data to Google Sheets, passing the grouped PRs JSON file
python3 upload_to_sheets.py "$OUTPUT_JSON"

# Deactivate the virtual environment (optional)
deactivate
