name: Update Plugins List and Create PR

on:
  schedule:
    - cron: '30 5 * * 3'  # Runs at 5:30 AM UTC on Wednesdays
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution of the workflow

jobs:
  update-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl parallel

      - name: Run find-plugin-repos.sh
        run: ./find-plugin-repos.sh

      - name: Run create-plugins-list-file.sh
        run: ./create-plugins-list-file.sh plugins.csv plugins.json

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"

      - name: Configure Git
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git checkout -b update-plugins-$(date +%Y-%m-%d)
          git add plugins.txt
          git commit -m "Update plugins list"
          git push origin update-plugins-$(date +%Y-%m-%d)

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-plugins-$(date +%Y-%m-%d)
          title: "Update plugins list"
          body: "Automatically generated by GitHub Actions."
          labels: automated-pr
